package com.pickanddrop.fragment;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.databinding.DataBindingUtil;
import androidx.drawerlayout.widget.DrawerLayout;

import com.pickanddrop.R;
import com.pickanddrop.activities.DrawerContentSlideActivity;
import com.pickanddrop.activities.SplashActivity;
import com.pickanddrop.databinding.TermsConditionsBinding;
import com.pickanddrop.utils.AppConstants;
import com.pickanddrop.utils.AppSession;
import com.pickanddrop.utils.Utilities;

public class TermsAndConditions  extends AppCompatActivity implements AppConstants{
    TermsConditionsBinding termsConditionsBinding;
    private AppSession appSession;

    private Context context;
    Button okayy;
    ImageView back;
    TextView test1,test2,test3,test4,test5,test6,test7;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        termsConditionsBinding = DataBindingUtil.setContentView(this, R.layout.terms_conditions);
        test1=(TextView)findViewById(R.id.test1);
        test2=(TextView)findViewById(R.id.test2);
        test1.setText("Legal\n" +
                "U.S. Terms of Use\n" +
                "Effective: November 1, 2017\n" +
                "1. Contractual Relationship\n" +
                "These Terms of Use (\"Terms\") govern your access or use, from within the United States and its territories and possessions, of the applications, websites, content, products, and services (the \"Services,\" as more fully defined below made available in the United States and its territories and possessions by Truckvancargo LLC PLEASE READ THESE TERMS CAREFULLY, AS THEY CONSTITUTE A LEGAL AGREEMENT BETWEEN YOU AND TRUCKVANCARGO. In these Terms, the words \"including\" and \"include\" mean \"including, but not limited to.\"\n" +
                "By accessing or using the Services, you confirm your agreement to be bound by these Terms. If you do not agree to these Terms, you may not access or use the Services. These Terms expressly supersede prior agreements or arrangements with you. Truckvancargo may immediately terminate these Terms or any Services with respect to you, or generally cease offering or deny access to the Services or any portion thereof, at any time for any reason.\n" +
                "IMPORTANT: PLEASE REVIEW THE ARBITRATION AGREEMENT SET FORTH BELOW CAREFULLY, AS IT WILL REQUIRE YOU TO RESOLVE DISPUTES WITH TRUCKVANCARGO ON AN INDIVIDUAL BASIS THROUGH FINAL AND BINDING ARBITRATION. BY ENTERING THIS AGREEMENT, YOU EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND ALL OF THE TERMS OF THIS AGREEMENT AND HAVE TAKEN TIME TO CONSIDER THE CONSEQUENCES OF THIS IMPORTANT DECISION.\n" +
                "Supplemental terms may apply to certain Services, such as policies for a particular event, program, activity or promotion, and such supplemental terms will be disclosed to you in separate region-specific disclosures (webpage on Truckvancargo.com) or in connection with the applicable Service(s). Supplemental terms are in addition to, and shall be deemed a part of, the Terms for the purposes of the applicable Service(s). Supplemental terms shall prevail over these Terms in the event of a conflict with respect to the applicable Services.\n" +
                "Truckvancargo may amend the Terms from time to time. Amendments will be effective upon Truckvancargo's posting of such updated Terms at this location or in the amended policies or supplemental terms on the applicable Service(s). Your continued access or use of the Services after such posting confirms your consent to be bound by the Terms, as amended. If Truckvancargo changes these Terms after the date you first agreed to the Terms (or to any subsequent changes to these Terms), you may reject any such change by providing Truckvancargo written notice of such rejection within 30 days of the date such change became effective, as indicated in the \"Effective\" date above. This written notice must be provided either (a) by mail or hand delivery to our registered agent for service of process, c/o Truckvancargo LLC. In order to be effective, the notice must include your full name and clearly indicate your intent to reject changes to these Terms. By rejecting changes, you are agreeing that you will continue to be bound by the provisions of these Terms as of the date you first agreed to the Terms (or to any subsequent changes to these Terms).\n" +
                "Truckvancargo’s collection and use of personal information in connection with the Services is described in Truckvancargo's Privacy Statements located at www.Truckvancargo.com\n" +
                " 2. Arbitration Agreement\n" +
                "By agreeing to the Terms, you agree that you are required to resolve any claim that you may have against Truckvancargo on an individual basis in arbitration, as set forth in this Arbitration Agreement. This will preclude you from bringing any class, collective, or representative action against Truckvancargo, and also preclude you from participating in or recovering relief under any current or future class, collective, consolidated, or representative action brought against Truckvancargo by someone else.\n" +
                "Agreement to Binding Arbitration Between You and Truckvancargo.\n" +
                "You and Truckvancargo agree that any dispute, claim or controversy arising out of or relating to these Terms or the existence, breach, termination, enforcement, interpretation or validity thereof, or your access to or use of the Services at any time, whether before or after the date you agreed to the Terms, will be settled by binding arbitration between you and Truckvancargo, and not in a court of law.\n" +
                "You acknowledge and agree that you and Truckvancargo are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Unless both you and Truckvancargo otherwise agree in writing, any arbitration will be conducted only on an individual basis and not in a class, collective, consolidated, or representative proceeding. However, you and Truckvancargo each retain the right to bring an individual action in small claims court and the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents or other intellectual property rights.\n" +
                "Rules and Governing Law.\n" +
                "The arbitration will be administered by the American Arbitration Association (\"AAA\") in accordance with the AAA’s Consumer Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the \"AAA Rules\") then in effect, except as modified by this Arbitration Agreement. The parties agree that the arbitrator (“Arbitrator”), and not any federal, state, or local court or agency, shall have exclusive authority to resolve any disputes relating to the interpretation, applicability, enforceability or formation of this Arbitration Agreement, including any claim that all or any part of this Arbitration Agreement is void or voidable. The Arbitrator shall also be responsible for determining all threshold arbitrability issues, including issues relating to whether the Terms are unconscionable or illusory and any defense to arbitration, including waiver, delay, laches, or estoppel.\n" +
                "Notwithstanding any choice of law or other provision in the Terms, the parties agree and acknowledge that this Arbitration Agreement evidences a transaction involving interstate commerce and that the Federal Arbitration will govern its interpretation and enforcement and proceedings pursuant thereto. It is the intent of the parties that the FAA and AAA Rules shall preempt all state laws to the fullest extent permitted by law. \n" +
                "Process. A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form Demand for Arbitration -.\n" +
                "Location and Procedure.\n" +
                "Unless you and Truckvancargo otherwise agree, the arbitration will be conducted in the county where you reside \n" +
                "Arbitrator's Decision.\n" +
                "The Arbitrator will render an award within the time frame specified in the AAA Rules. Judgment on the arbitration award may be entered in any court having competent jurisdiction to do so. The Arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant's individual claim. An Arbitrator’s decision shall be final and binding on all parties. An Arbitrator’s decision and judgment thereon shall have no precedential or collateral estoppel effect. If you prevail in arbitration you will be entitled to an award of attorneys' fees and expenses, to the extent provided under applicable law. Truckvancargo will not seek, and hereby waives all rights Truckvancargo may have under applicable law to recover, attorneys' fees and expenses if Truckvancargo prevails in arbitration.\n" +
                "Fees.\n" +
                "Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules\n" +
                "Changes.\n" +
                "Notwithstanding the provisions in Section I above, regarding consent to be bound by amendments to these Terms, if Truckvancargo changes this Arbitration Agreement after the date you first agreed to the Terms (or to any subsequent changes to the Terms), you may reject any such change by providing Truckvancargo written notice of such rejection within 30 days of the date such change became effective, as indicated in the \"Effective\" date above. This written notice must be provided either (a) by mail or hand delivery to our registered agent for service of process. In order to be effective, the notice must include your full name and clearly indicate your intent to reject changes to this Arbitration Agreement. By rejecting changes, you are agreeing that you will arbitrate any dispute between you and Truckvancargo in accordance with the provisions of this Arbitration Agreement as of the date you first agreed to the Terms (or to any subsequent changes to the Terms).\n" +
                "\n" +
                "3. The Services\n" +
                "The Services comprise mobile applications and related services (each, an \"Application\"), which enable users to arrange and schedule transportation, logistics and/or delivery services and/or to purchase certain goods, including with third party providers of such services and goods under agreement with Truckvancargo or certain of Truckvancargo's affiliates (\"Third Party Providers\"). In certain instances the Services may also include an option to receive transportation, logistics and/or delivery services for an upfront price, subject to acceptance by the respective Third Party Providers. Unless otherwise agreed by Truckvancargo in a separate written agreement with you, the Services are made available solely for your personal, noncommercial use. YOU ACKNOWLEDGE THAT YOUR ABILITY TO OBTAIN TRANSPORTATION, LOGISTICS AND/OR DELIVERY SERVICES THROUGH THE USE OF THE SERVICES DOES NOT ESTABLISH TRUCKVANCARGO AS A PROVIDER OF TRANSPORTATION, LOGISTICS OR DELIVERY SERVICES OR AS A TRANSPORTATION CARRIER.\n" +
                "License.\n" +
                "Subject to your compliance with these Terms, Truckvancargo grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable license to: 1- access and use the Applications on your personal device solely in connection with your use of the Services; and 2- access and use any content, information and related materials that may be made available through the Services, in each case solely for your personal, noncommercial use. Any rights not expressly granted herein are reserved by Truckvancargo and Truckvancargo's licensors.\n" +
                "Provision of the Services.\n" +
                "You acknowledge that portions of the Services may be made available under Truckvancargo's various brands or request options associated with transportation or logistics, including the transportation request brands currently referred to as \"Truckvancargo.\n" +
                "The Services may be made available or accessed in connection with third party services and content (including advertising) that Truckvancargo does not control. You acknowledge that different terms of use and privacy policies may apply to your use of such third party services and content. Truckvancargo does not endorse such third party services and content and in no event shall Truckvancargo be responsible or liable for any products or services of such third party providers. Additionally, Apple Inc., Google, Inc., Microsoft Corporation or BlackBerry Limited will be a third-party beneficiary to this contract if you access the Services using Applications developed for Apple iOS, Android, Microsoft Windows, or Blackberry-powered mobile devices, respectively. These third party beneficiaries are not parties to this contract and are not responsible for the provision or support of the Services in any manner. Your access to the Services using these devices is subject to terms set forth in the applicable third party beneficiary's terms of service.\n" +
                "Ownership.\n" +
                "The Services and all rights therein are and shall remain Truckvancargo's property or the property of Truckvancargo's licensors. Neither these Terms nor your use of the Services convey or grant to you any rights: (i) in or related to the Services except for the limited license granted above; or (ii) to use or reference in any manner Truckvancargo's company names, logos, product and service names, trademarks or services marks or those of Truckvancargo's licensors.\n" +
                "4. Access and Use of the Services\n" +
                "User Accounts.\n" +
                "In order to use most aspects of the Services, you must register for and maintain an active personal user Services account (\"Account\"). You must be at least 18 years of age, or the age of legal majority in your jurisdiction (if different than 18), to obtain an Account, unless a specific Service permits otherwise. Account registration requires you to submit to Truckvancargo certain personal information, such as your name, address, mobile phone number and age, as well as at least one valid payment method supported by Truckvancargo. You agree to maintain accurate, complete, and up-to-date information in your Account. Your failure to maintain accurate, complete, and up-to-date Account information, including having an invalid or expired payment method on file, may result in your inability to access or use the Services. You are responsible for all activity that occurs under your Account, and you agree to maintain the security and secrecy of your Account username and password at all times. Unless otherwise permitted by Truckvancargo in writing, you may only possess one Account.\n" +
                "User Requirements and Conduct.\n" +
                "The Service is not available for use by persons under the age of 18. You may not authorize third parties to use your Account, and you may not allow persons under the age of 18 to receive transportation or logistics services from Third Party Providers unless they are accompanied by you. You may not assign or otherwise transfer your Account to any other person or entity. You agree to comply with all applicable laws when accessing or using the Services, and you may only access or use the Services for lawful purposes (e.g., no transport of unlawful or hazardous materials). You may not in your access or use of the Services cause nuisance, annoyance, inconvenience, or property damage, whether to the Third Party Provider or any other party. In certain instances you may be asked to provide proof of identity to access or use the Services, and you agree that you may be denied access to or use of the Services if you refuse to provide proof of identity.\n" +
                "Text Messaging and Telephone Calls.\n" +
                "You agree that Truckvancargo may contact you by telephone or text messages (including by an automatic telephone dialing system) at any of the phone numbers provided by you or on your behalf in connection with an Truckvancargo account, including for marketing purposes. You understand that you are not required to provide this consent as a condition of purchasing any property, goods or services. You also understand that you may opt out of receiving text messages from Truckvancargo at any time. \n" +
                "Referrals and Promotional Codes.\n" +
                "Truckvancargo may, in its sole discretion, create referral and/or promotional codes (\"Promo Codes\") that may be redeemed for discounts on future Services and/or a Third Party Provider's services, or other features or benefits related to the Services and/or a Third Party Provider's services, subject to any additional terms that Truckvancargo establishes. You agree that Promo Codes: 1- must be used for the intended audience and purpose, and in a lawful manner; 2- may not be duplicated, sold or transferred in any manner, or made available to the general. 3- may be disabled by Truckvancargo at any time for any reason without liability to Truckvancargo. 4- may only be used pursuant to the specific terms that Truckvancargo establishes for such Promo Code; 5- are not valid for cash, 6- may expire prior to your use. Truckvancargo reserves the right to withhold or deduct credits or other features or benefits obtained through the use of the referral system or Promo Codes by you or any other user in the event that Truckvancargo determines or believes that the use of the referral system or use or redemption of the Promo Code was in error, fraudulent, illegal, or otherwise in violation of Truckvancargo’s Terms.\n" +
                "User Provided Content.\n" +
                "Truckvancargo may, in Truckvancargo's sole discretion, permit you from time to time to submit, upload, publish or otherwise make available to Truckvancargo through the Services textual, audio, and/or visual content and information, including commentary and feedback related to the Services, initiation of support requests, and submission of entries for competitions and promotions (\"User Content\"). Any User Content provided by you remains your property. However, by providing User Content to Truckvancargo, you grant Truckvancargo a worldwide, perpetual, irrevocable, transferable, royalty-free license, with the right to sublicense, to use, copy, modify, create derivative works of, distribute, publicly display, publicly perform, and otherwise exploit in any manner such User Content in all formats and distribution channels now known or hereafter devised (including in connection with the Services and Truckvancargo's business and on third-party sites and services), without further notice to or consent from you, and without the requirement of payment to you or any other person or entity.\n" +
                "You represent and warrant that: 1- you either are the sole and exclusive owner of all User Content or you have all rights, licenses, consents and releases necessary to grant Truckvancargo the license to the User Content as set forth above; and 2- neither the User Content, nor your submission, uploading, publishing or otherwise making available of such User Content, nor Truckvancargo's use of the User Content as permitted herein will infringe, misappropriate or violate a third party's intellectual property or proprietary rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.\n" +
                "You agree to not provide User Content that is defamatory, libelous, hateful, violent, obscene, pornographic, unlawful, or otherwise offensive, as determined by Truckvancargo in its sole discretion, whether or not such material may be protected by law. Truckvancargo may, but shall not be obligated to, review, monitor, or remove User Content, at Truckvancargo's sole discretion and at any time and for any reason, without notice to you.\n" +
                "Network Access and Devices you are responsible for obtaining the data network access necessary to use the Services. Your mobile network's data and messaging rates and fees may apply if you access or use the Services from your device. You are responsible for acquiring and updating compatible hardware or devices necessary to access and use the Services and Applications and any updates thereto. Truckvancargo does not guarantee that the Services, or any portion thereof, will function on any particular hardware or devices. In addition, the Services may be subject to malfunctions and delays inherent in the use of the Internet and electronic communications.\n" +
                "5. Payment\n" +
                "You understand that use of the Services may result in charges to you for the services or goods you receive (\"Charges\"). Truckvancargo will receive and/or enable your payment of the applicable Charges for services or goods obtained through your use of the Services. Charges will be inclusive of applicable taxes where required by law. Charges may include other applicable fees, tolls, and/or surcharges including a booking fee, municipal tolls, or processing fees for split payments. All Charges and payments will be enabled by Truckvancargo using the preferred payment method designated in your Account, after which you will receive a receipt by email. If your primary Account payment method is determined to be expired, invalid or otherwise not able to be charged, you agree that Truckvancargo may use a secondary payment method in your Account, if available. Charges paid by you are final and non-refundable, unless otherwise determined by Truckvancargo.\n" +
                "As between you and Truckvancargo, Truckvancargo reserves the right to establish, remove and/or revise Charges for any or all services or goods obtained through the use of the Services at any time in Truckvancargo's sole discretion. Further, you acknowledge and agree that Charges applicable in certain geographical areas may increase substantially during times of high demand. Truckvancargo will use reasonable efforts to inform you of Charges that may apply, provided that you will be responsible for Charges incurred under your Account regardless of your awareness of such Charges or the amounts thereof. Truckvancargo may from time to time provide certain users with promotional offers and discounts that may result in different amounts charged for the same or similar services or goods obtained through the use of the Services, and you agree that such promotional offers and discounts, unless also made available to you, shall have no bearing on your use of the Services or the Charges applied to you. You may elect to cancel your request for Services at any time prior to the commencement of such Services, in which case you may be charged a cancellation fee on a Third Party Provider’s behalf. After you have received services or goods obtained through the Service, you will have the opportunity to rate your experience and leave additional feedback. Truckvancargo may use the proceeds of any Charges for any purpose, subject to any payment obligations it has agreed to with any Third Party Providers or other third parties.\n" +
                "In certain cases, with respect to Third Party Providers, Charges you incur will be owed directly to Third Party Providers, and Truckvancargo will collect payment of those charges from you, on the Third Party Provider’s behalf as their limited payment collection agent, and payment of the Charges shall be considered the same as payment made directly by you to the Third Party Provider. In such cases, you retain the right to request lower Charges from a Third Party Provider for services or goods received by you from such Third Party Provider at the time you receive such services or goods, and Charges you incur will be owed to the Third Party Provider. Truckvancargo will respond accordingly to any request from a Third Party Provider to modify the Charges for a particular service or good. This payment structure is intended to fully compensate a Third Party Provider, if applicable, for the services or goods obtained in connection with your use of the Services. In all other cases, Charges you incur will be owed and paid directly to Truckvancargo or its affiliates, where Truckvancargo is solely liable for any obligations to Third Party Providers. In such cases, you retain the right to request lower Charges from Truckvancargo for services or goods received by you from a Third Party Provider at the time you receive such services or goods, and Truckvancargo will respond accordingly to any request from you to modify the Charges for a particular service or good. Except with respect to taxicab transportation services requested through the Application, Truckvancargo does not designate any portion of your payment as a tip or gratuity to a Third Party Provider. Any representation by Truckvancargo (on Truckvancargo's website, in the Application, or in Truckvancargo's marketing materials) to the effect that tipping is \"voluntary,\" \"not required,\" and/or \"included\" in the payments you make for services or goods provided is not intended to suggest that Truckvancargo provides any additional amounts, beyond those described above, to a Third Party Provider you may use. You understand and agree that, while you are free to provide additional payment as a gratuity to any Third Party Provider who provides you with services or goods obtained through the Service, you are under no obligation to do so. Gratuities are voluntary.\n" +
                "Repair or Cleaning Fees.\n" +
                "You shall be responsible for the cost of repair for damage to, or necessary cleaning of, vehicles and property resulting from use of the Services under your Account in excess of normal \"wear and tear\" damages and necessary cleaning (\"Repair or Cleaning\"). In the event that a Repair or Cleaning request is verified by Truckvancargo in Truckvancargo's reasonable discretion, Truckvancargo reserves the right to facilitate payment for the reasonable cost of such Repair or Cleaning using your payment method designated in your Account. Such amounts will be transferred by Truckvancargo to a Third Party Provider, if applicable, and are non-refundable.\n" +
                "6. Disclaimers; Limitation of Liability; Indemnity.\n" +
                "DISCLAIMER.\n" +
                "THE SERVICES ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE.\" TRUCKVANCARGO DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, NOT EXPRESSLY SET OUT IN THESE TERMS, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN ADDITION, TRUCKVANCARGO MAKES NO REPRESENTATION, WARRANTY, OR GUARANTEE REGARDING THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, OR AVAILABILITY OF THE SERVICES OR ANY SERVICES OR GOODS REQUESTED THROUGH THE USE OF THE SERVICES, OR THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE. TRUCKVANCARGO DOES NOT GUARANTEE THE QUALITY, SUITABILITY, SAFETY OR ABILITY OF THIRD PARTY PROVIDERS. YOU AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SERVICES, AND ANY SERVICE OR GOOD REQUESTED IN CONNECTION THEREWITH, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW.\n" +
                "LIMITATION OF LIABILITY.\n" +
                "TRUCKVANCARGO SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOST DATA, PERSONAL INJURY, OR PROPERTY DAMAGE RELATED TO, IN CONNECTION WITH, OR OTHERWISE RESULTING FROM ANY USE OF THE SERVICES, REGARDLESS OF THE NEGLIGENCE (EITHER ACTIVE, AFFIRMATIVE, SOLE, OR CONCURRENT) OF TRUCKVANCARGO, EVEN IF TRUCKVANCARGO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.\n" +
                "TRUCKVANCARGO SHALL NOT BE LIABLE FOR ANY DAMAGES, LIABILITY OR LOSSES ARISING OUT OF: (i) YOUR USE OF OR RELIANCE ON THE SERVICES OR YOUR INABILITY TO ACCESS OR USE THE SERVICES; OR (ii) ANY TRANSACTION OR RELATIONSHIP BETWEEN YOU AND ANY THIRD PARTY PROVIDER, EVEN IF TRUCKVANCARGO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TRUCKVANCARGO SHALL NOT BE LIABLE FOR DELAY OR FAILURE IN PERFORMANCE RESULTING FROM CAUSES BEYOND TRUCKVANCARGO'S REASONABLE CONTROL. YOU ACKNOWLEDGE THAT THIRD PARTY PROVIDERS PROVIDING TRANSPORTATION SERVICES REQUESTED THROUGH SOME REQUEST PRODUCTS MAY OFFER RIDESHARING OR PEER-TO-PEER TRANSPORTATION SERVICES AND MAY NOT BE PROFESSIONALLY LICENSED OR PERMITTED.\n" +
                "THE SERVICES MAY BE USED BY YOU TO REQUEST AND SCHEDULE TRANSPORTATION, GOODS, OR LOGISTICS SERVICES WITH THIRD PARTY PROVIDERS, BUT YOU AGREE THAT TRUCKVANCARGO HAS NO RESPONSIBILITY OR LIABILITY TO YOU RELATED TO ANY TRANSPORTATION, GOODS OR LOGISTICS SERVICES PROVIDED TO YOU BY THIRD PARTY PROVIDERS OTHER THAN AS EXPRESSLY SET FORTH IN THESE TERMS.\n" +
                "THE LIMITATIONS AND DISCLAIMER IN THIS SECTION DO NOT PURPORT TO LIMIT LIABILITY OR ALTER YOUR RIGHTS AS A CONSUMER THAT CANNOT BE EXCLUDED UNDER APPLICABLE LAW. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, TRUCKVANCARGO’S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW. THIS PROVISION SHALL HAVE NO EFFECT ON TRUCKVANCARGO’S CHOICE OF LAW PROVISION SET FORTH BELOW.\n" +
                "Indemnity.\n" +
                "You agree to indemnify and hold Truckvancargo and its affiliates and their officers, directors, employees, and agents harmless from any and all claims, demands, losses, liabilities, and expenses (including attorneys' fees), arising out of or in connection with: 1- your use of the Services or services or goods obtained through your use of the Services; 2- your breach or violation of any of these Terms; 3- Truckvancargo's use of your User Content; or 4- your violation of the rights of any third party, including Third Party Providers.\n" +
                "7. Other Provisions\n" +
                "Law.\n" +
                "These Terms are governed by and construed in accordance with the laws of the, U.S.A., without giving effect to any conflict of law principles, except as may be otherwise provided in the Arbitration Agreement above or in supplemental terms applicable to your region. The foregoing choice of law and forum selection provisions do not apply to the arbitration clause in Section 2 or to any abatable disputes as defined therein. Instead, as described in Section 2, the Federal Arbitration Act shall apply to any such disputes.\n" +
                "Claims of Copyright Infringement.\n" +
                "Claims of copyright infringement should be sent to Truckvancargo's designated agent. Please visit Truckvancargo's web page at https://www.Truckvancargo.com for the designated address and additional information.\n" +
                "Notice.\n" +
                "Truckvancargo may give notice by means of a general notice on the Services, electronic mail to your email address in your Account, telephone or text message to any phone number provided in connection with your account, or by written communication sent by first class mail or pre-paid post to any address connected with your Account. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing or posting (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email or telephone). You may give notice to Truckvancargo, with such notice deemed given when received by Truckvancargo, at any time by first class mail or pre-paid post to our registered agent for service of process, c/o Truckvancargo USA, LLC. The name and current contact information for the registered agent in each state are available online here.\n" +
                "General.\n" +
                "You may not assign these Terms without Truckvancargo's prior written approval. Truckvancargo may assign these Terms without your consent to: 1- a subsidiary or affiliate; 2- an acquirer of Truckvancargo's equity, business or assets; or 3- a successor by merger. Any purported assignment in violation of this section shall be void. No joint venture, partnership, employment, or agency relationship exists between you, Truckvancargo or any Third Party Provider as a result of this Agreement or use of the Services. If any provision of these Terms is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. Truckvancargo's failure to enforce any right or provision in these Terms shall not constitute a waiver of such right or provision less acknowledged and agreed to by Truckvancargo in writing. This provision shall not affect the Severability and Survivability section of the Arbitration Agreement of these Terms.\n" +
                "\n" +
                "The above terms and conditions are subject to change and all users of Truckvancargo will automatically be subject to any changes\n");


        test2.setText("Effective Date: Nov. 2, 2017\n" +
                "Your privacy is important to us and maintaining your trust is our priority. To ensure that your privacy choices are respected, Truckvancargo,LLC . ( \"Truckvancargo,\" \"we,\" or \"us\") has set out in this Privacy Policy, an explanation of our online information practices as well as the decisions you may make regarding how your information is collected and used when viewing the www.truckvancargo.com  website, website, and other  Mobile Applications (collectively, the \"Site\").\n" +
                "With respect to personal data received or transferred pursuant to the Privacy Shield Frameworks, Truckvancargo is subject to the regulatory enforcement powers of the U.S. Federal Trade Commission. In certain situations, Truckvancargo may be required to disclose personal data in response to lawful requests by public authorities, including to meet national security or law enforcement requirements.\n" +
                "Under certain conditions, more fully described on the  you may be entitled to invoke binding arbitration when other dispute resolution procedures have been exhausted.\n" +
                "Capitalized terms that are not defined in this Privacy Policy have the meaning given to them in our Terms of Use or in any other contractual document between you and us.\n" +
                "We reserve the right to change this Privacy Policy at any time. Such changes, modifications, additions or deletions shall be effective immediately upon notice thereof, which may be given by means including, but not limited to, issuing an email to the email address listed by registered users and/or by posting a notice and the revised Privacy Policy on the applicable Truckvancargo website. You acknowledge that it is your responsibility to maintain a valid email address as a registered user, and to review the Site and this Privacy Policy periodically in order to be aware of any modifications. Your continued use of the Services after such modifications will constitute your:\n" +
                "acknowledgment of the modified Privacy Policy; and\n" +
                "agreement to abide and be bound by the modified Privacy Policy. You can see when this Privacy Policy was last updated by checking the date at the top of this page.\n" +
                "1) INFORMATION WE COLLECT ABOUT YOU AND HOW WE COLLECT IT \n" +
                "We collect several types of information from and about users of the Site and the products and services of Truckvancargo (collectively, the \"Services\"), including:\n" +
                "Information by which you can be personally identified, such as your name, physical address, e-mail address, and phone number (\"Personal Information\"). The specific Personal Information that we collect depends on the type of Services that you may be using; and\n" +
                "Information, which does not identify you (\"Technical Information\"). We collect this Technical Information: \n" +
                "directly from you when you provide it to us;\n" +
                "automatically as you navigate through the Site and\n" +
                "from third parties\n" +
                "Your knowledge and consent of our collection, use and disclosure of your Personal information is critical in order for us to provide the Services to you. We rely on any of the following actions by you as indications of your consent to our existing and future Personal Information practices: your voluntary provision of Personal Information directly to us; your express consent or acknowledgement contained within a written, verbal or electronic application process; your consent solicited by us (or our agent) for a specified purpose; or your acceptance of the Privacy Policy until you notify us in writing of a withdrawal of this consent.\n" +
                "Information You Provide to Us.  In the course of using the Services, you may provide us with information about yourself, including, but not limited to: \n" +
                "Information that you provide by filling in forms on our Site, responding to surveys, creating an account, subscribing to the Services, posting material, communicating with our personnel, sending, receiving, or engaging with messages, requesting further services, entering a contest, taking part in a promotion, or reporting a problem\n" +
                "Details of transactions you carry out through our Site\n" +
                "User Contributions, i.e., you may provide information to be published or displayed on public areas of the Site, or transmitted to other users of the Site or third parties (collectively, \"User Contributions\")\n" +
                "If you authorize Truckvancargo to connect your account to the account of a \"Connected Site\" we may be able to access information you have provided to the Connected Site, such as content information, timeline feeds, contact and follow lists, network statistics and updates regarding your Connected Site account\n" +
                "Information We Collect through Automatic Data Technologies. As you navigate through and interact with our Services, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions and patterns, including: \n" +
                "Details of your visits to our Site and use of the Services, including traffic data, location data, logs and the resources that you access and use on our Site or the Services\n" +
                "2) HOW WE USE YOUR INFORMATION \n" +
                "We use information that we collect about you or that you provide to us, including any Personal Information:\n" +
                "To administer our Site and its contents to you\n" +
                "To provide you with information, products or services that you need depending on the type of Services you use\n" +
                "To provide you with notices about your account and/or your subscription, including expiration and renewal notices\n" +
                "To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection\n" +
                "To notify you about changes to our Site, products or services\n" +
                "To allow you to participate in interactive features on our Site\n" +
                "To diagnose service or technical problems, trouble shooting, analyzing how our Services is used, personalizing content for you, providing the end service to you (which may include sharing certain information with third party vendors and service providers) and to respond to any enquiries that you may have\n" +
                "To improve our Site and the Services by enabling us to: store information about your preferences, allowing us to deliver a more personalized service to you; speed up your searches; and recognize you when you return to the Site\n" +
                "In any other way we may describe when you provide the information\n" +
                "For any other purpose with your consent\n" +
                "IMPORTANT: Any Personal Information or content that you voluntarily disclose for public posting to our Services, such as User Content, becomes available to the public and may be accessed, used and stored by others around the world. Accordingly, you should not post sensitive personal information or any other information that you would not want made public to any other Site or application or to a public website. You should never provide your social security number, national insurance number, financial information, and other sensitive information.\n" +
                "Technical Information. We may share Technical Information (such as usage data and demographics, referring/exit pages and URLs, platform types, number of clicks, etc.) with interested third parties to help them understand the usage patterns for certain Truckvancargo services or to drive product engagement with other Users of the Services.\n" +
                "3) HOW WE PROTECT YOUR INFORMATION \n" +
                "We use appropriate technical and organizational measures to protect any Personal Information we process about you. All information you provide to us is stored on our secure servers behind firewalls. Any payment transactions and credit or debit card data will be encrypted.\n" +
                "Unfortunately, no data transmission over the Internet or any wireless network can be guaranteed to be 100% secure. As a result, while we strive to protect your Personal Information, you acknowledge that:\n" +
                "there are security and privacy limitations of the Internet which are beyond our control;\n" +
                "4) MESSAGING SERVICE \n" +
                "We collect, process and store information when you send, receive, or engage with messages in connection with our Services. This includes information such as the number of messages you’ve sent and received, when you have viewed a message, details of who you’ve chatted with and when and which messages were responded to (\"Message Data\"). We may share limited portions of Message Data with third parties including other users of our Services, such as identifying active users of the message service, highlighting responsiveness to messages, or notifying a sender when a message has been viewed.\n" +
                "We also store your messages (\"Message Content\") to generally permit you to access your message history; however, we cannot guarantee access to all messages at all times, and messages may be removed or deleted, including in connection with changes in or interruptions of service with our vendors, changes to our Services or features, or Truckvancargo’s or our vendors’ data retention processes or storage limitations. We may view Message Content to investigate or resolve technical or trust and safety issues or to improve our Services. We will never share Message Content with third parties except as required by law or with your consent.\n" +
                "We also may use automatic scanning technology on messages to allow us to recognize patterns on our messaging platform. These patterns may help us make your professional communications more efficient and informed and contribute to a safer and more secure job search experience. For example, our software may do the following:\n" +
                "Look for text that indicates a web link (e.g. ends with \".com\" or similar) to generate a clickable link\n" +
                "Provide auto-complete options when it anticipates who the receiver of the message may be\n" +
                "Look for content to provide quick actions such as a scheduling tool\n" +
                "Look for content to provide quick replies based on context\n" +
                "Check links shared in messages for malicious sites and looks for blacklisted keywords to detect spam and fraud.\n" +
                "5) PUBLIC FORUMS \n" +
                "You should be aware that when you voluntarily disclose any Personal Information in a public forum on the Site, this information, along with any information disclosed in your communication, can be collected and used by third parties and may result in unsolicited messages from third parties. Such activities are beyond our control and this Privacy Policy does not apply to such information. You accept that you, and not Truckvancargo, are responsible for providing such information in any public forum. Any submissions to public areas on the Site are accepted by you with the understanding that such forums are accessible to all third parties. If you do not want your comments or any content to be viewed by third parties, you are advised not to make any submissions. Ultimately, you are solely responsible for maintaining the secrecy of your password and/or account information. Please be careful and responsible whenever you're online.\n" +
                "6) COOKIES AND SIMILAR TECHNOLOGIES \n" +
                "Tracking Technologies. Truckvancargo and its partners use cookies or similar technologies to analyze trends, administer the website, track users' movements around the website, and to gather demographic information about our user base as a whole. You can control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functions on our website or service.\n" +
                "Blocking Cookies. You can also set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our Site through your access to some functionality and areas of our Site may be restricted. As the means by which you can refuse cookies through your web browser controls vary from browser-to-browser, you should visit your browser's help menu for more information.\n" +
                "Passive Information. As is true of most websites, we gather certain information automatically. This information may include Internet protocol (IP) addresses, browser type, Internet service provider (ISP), referring/exit pages, the files viewed on our site (e.g., HTML pages, graphics, etc.), operating system, date/time stamp, and/or clickstream data to analyze trends in the aggregate and administer the site.\n" +
                "\n" +
                "\n" +
                "Mobile Analytics. We use mobile analytics software to allow us to better understand the functionality of our Mobile Software on your phone. This software may record information such as how often you use the application, the events that occur within the application, aggregated usage, performance data, and where the application was downloaded from.\n" +
                "Push Notifications. We may send you push notifications from time-to-time in order to update you about any events or promotions that we may be running. If you no longer wish to receive these types of communications, you may turn them off at the device level. To ensure you receive proper notifications, we will need to collect certain information about your device such as operating system and user identification information.\n" +
                "7) SOCIAL MEDIA (FEATURES) AND WIDGETS \n" +
                "Our Services includes social media features, such as the Facebook Like button and Widgets, and the ShareThisButton. These features may collect your IP address, which page you are visiting on our Services, and may set a cookie to enable the Feature to function properly. Social media features and widgets are either hosted by a third party or hosted directly on our Services. Your interactions with these features are governed by the privacy policy of the company providing such features.\n" +
                "friend may contact us to request that we remove this information from our database at privacy@truckvancargo.com.\n" +
                "         \n" +
                "8) HOW TO CONTACT US \n" +
                "If you have any questions about this Privacy Policy or our privacy practices, please contact us at www.truckvancargo.com, or send mail to: truckvancargo@yahoo.com\n" +
                "The above policies are subject to change and all users of Truckvancargo will automatically be subject to any changes.\n" +
                "U.S. Mailing Address\t\n" +
                "Truckvancargo, LLC.;\n" +
                "Attn: Business Affairs\n" +
                "7 Peru Street . \n" +
                "Edison ,NJ 08820, USA \t\n" +
                "Customer Support Questions: If you have questions about your User account, any other Services-related questions, please contact Customer Service at support@truckvancargo.com or call the following numbers:\n" +
                "US: 1-732-200-2316 (8am - 6pm PST)\n" +
                "\n" +
                "Truckvancargo,LLC. © All Rights Reserved Worldwide ");

        okayy = (Button) findViewById(R.id.terms_okay);
        okayy.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onBackPressed();
            }
        });
        back = (ImageView) findViewById(R.id.iv_back);
        back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                onBackPressed();
            }
        });

    }
}
